version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: upwork
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mounir
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile for the FastAPI app
    depends_on:
      - postgres
    environment:
      host: postgres
      port: "5432"
    ports:
      - "8000:8000"

volumes:
  postgres_data: